apiVersion: apps/v1
kind: Deployment
metadata:
  name: rps-deployment
  labels:
    app: rps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rps
  template:
    metadata:
      labels:
        app: rps
    spec:
      containers:
      - name: rps
        image: rps:local # make sure that tag is not latest as lastest is ignored by minikube
        imagePullPolicy: Never # doesn't try to pull from dockerhub
        ports:
        - containerPort: 8080
